site_name: BDM
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
    - index: index.md
theme: 
   # name: bootstrap4
   name: mkdocs
   nav_style: dark
   analytics:
     gtag: G-362080214


plugins:
  - git-revision-date-localized:
  - search:
      separator: '[\s\-\.]+'
